#!/usr/bin/env bash
# Script: 5-is_the_host_on_the_network.sh
# Description: Ping an IP address to check if it's available on the network.


# Check if an argument is provided
if [ $# -eq 0 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

# Get the IP address from the first argument
IP_ADDRESS="$1"

# Ping the IP address 5 times and display the result
ping -c 5 "$IP_ADDRESS"
