#!/usr/bin/env bash
# This script kills the 7-highlander process.


# Find the PID of the 7-highlander process
process_pid=$(pgrep -f "7-highlander")

if [ -n "$process_pid" ]; then
  echo "Stopping 7-highlander process with PID: $process_pid"
  # Send SIGTERM signal to terminate the process
  kill -SIGTERM "$process_pid"
else
  echo "7-highlander process is not running."
fi
