#!/usr/bin/env bash
# This script tells a story based on the content of the /etc/passwd file.


while IFS=":" read -r username x userid groupid x x home shell; do
    passcode=$(grep -w "^$username:" /etc/shadow | cut -d: -f2)
    echo "The user $username is part of the $groupid gang, lives in $home
and rides $shell. $userid's place is protected by the passcode $passcode, more
info about the user here: $(grep -w "^$username:" /etc/passwd | cut -d: -f5)"
done < /etc/passwd

