#!/usr/bin/env bash
# Script that display "Best School" 10x, but says "Hi" on the 9th iteration


count=0
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
